version: "3.8"
services:
  web:
    container_name: web
    build:
      context: app_to_do_list/
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    ports:
     - "5000:5000"
    depends_on:
      - celery
    volumes:
      - ./app_to_do_list/web:/web
    environment:
      DATABASE_HOST: mysql
      POSTGRES_USER: test1
      POSTGRES_PASSWORD: Test1_2020
      POSTGRES_DB: crud

  celery:
      container_name: celery
      build:
        context: app_to_do_list/.
        dockerfile: Dockerfile
      command: celery -A settings.celery worker --loglevel=info
      volumes:
         - ./app_to_do_list/web:/web
      network_mode: host
